name: Fetch Data and Upload CSV

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes (change as needed)

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the Python script
        run: |
          python fetch-data.py

      - name: Commit and push updated CSV file
        run: |
          git add data.csv
          git commit -m "Update data.csv with latest results"
          git push origin main
